### ISSUE TITLE
Iridium copies profile on startup

### ISSUE THREAD

**Issue by captn3m0** [strukturag/iridium-browser-ubuntu#7] opened 2015-05-04 11:27 UTC
I am not sure how and why this happened, but when I installed iridium (ubuntu 14.04 via PPA) on first boot and it already came preloaded with History from my other browser. I am not sure which one (since I have multiple chrome/chromium installs already).

My History file in `/home/nemo/.config/iridium/Default` is 136KB in size and I haven't opened a single link in iridium. Its creation date is consistent with the install time as well.

**Comment by fancycode** [comment] 2015-06-08 08:04
Hmm, I don't see any obvious reason why iridium should import the history automatically and can't reproduce it here locally with the latest version 43.3. Could you please remove the folder `/home/nemo/.config/iridium` to clear all settings (make sure to backup it before removing), restart iridium-browser and check if this still happens with the latest version for you?
If so, it would help if you could find out where it imported the history from.

**Comment by shvgn** [comment] 2015-06-20 10:02
I confirm. Fresh install of Iridium 43.5 already knows sites I visited earlier in another browser.

I rarely turn on Ubuntu (mint), so I compared the history with ones from other installed browsers. First I checked chromium-based browsers (Yandex, Vivaldi and Opera), but history lists don't coincide. It turned out that the history in iIridium is similar only to one in firefox.

**Comment by shvgn** [comment] 2015-06-20 10:16
1. Removed ~.mozilla and ~.config/iridium, checked that history in Iridium and Firefox was clear on new launch.
2. Opened Twitter in Iridium and closed the browser.
3. Visited Github and couple of other sites in Firefox, closed it. 
4. Iridium now knows about Twitter but doesn't know about github and others from Firefox. Maybe the history is imported only on first launch, like migration feature in Chromium? Let's check...
5. rm -rf .config/iridium
6. Launch Iridium and see visited sites from the Firefox history!

**Comment by fancycode** [comment] 2015-06-25 13:52
http://lists.inai.de/pipermail/iridium/2015-June/000428.html

**Comment by fancycode** [comment] 2015-07-10 11:05
https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/tree/browser-disable-profile-auto-import-on-first-run.patch?h=patchview

**Closed as completed by fancycode** 2015-07-10 11:05 UTC
